#!/bin/sh

echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged ||
(
    echo '🤢🤮🤢🤮 Its RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
